### ISSUE TITLE
changing the image state resets the entries filter and the search terms

### ISSUE THREAD

**Issue by jamesongithub** [SUSE-Enceladus/public-cloud-info-service#15]
Currently if you change the image state filters - active, inactive, deleted, etc. it resets the # of entries selection as well as any search terms, it would be good to save these selections when you change the image state filter.

this doesn't seem to occur when you change the location/environment.

**Comment by ikapelyukhin** [comment]
@jamesongithub this is an issue with PINT web UI, i.e. https://pint.suse.com?

**Comment by jamesongithub** [comment]
hi yes, referring to these filters

![image](https://user-images.githubusercontent.com/4452738/111376766-1e197f00-865d-11eb-9e21-6e71029ff68b.png)

**Comment by jeremy-moffitt** [comment]
I need to figure out how to pass the search string into the jsviews table widget that we're using, as that gets redrawn each time the underlying dataset changes. The search and entries filters are done client side in that widget, whereas the other values trigger a reload from server. I agree that the search/entries values should be preserved, I just need to figure out how to do it.

**Comment by jamesongithub** [comment]
ah ok, makes sense, the client side filtering is nice, and fast

**Comment by jeremy-moffitt** [comment]
I have a fix for this pending on the UI repo, will update here once it lands

**Comment by jeremy-moffitt** [comment]
Initial fix has landed. There's a corner case if you load up a dataset that has zero entries (such as oracle servers), the fix for that is being reviewed. Once that change lands I'll close this issue.

**Comment by jamesongithub** [comment]
nice! thought this was the ui repo. i guess it's just the server side.

**Comment by jeremy-moffitt** [comment]
https://pint.suse.com/  is fully updated now, with the server and entries parameters carrying over between selections. If you run into any related issues please let me know.

**Comment by jamesongithub** [comment]
hey jeremy just tested it out looks like it works now! thanks!

i noticed that when you go from active, delete, inactive, deprecated to all states it triggers a reload of the images.xml but not the other way around now. 

seems to be different for different clouds, gcp triggers for all states
