### ISSUE TITLE
The primary keys for images need to be corrected

### ISSUE THREAD

**Issue by jeremy-moffitt** [SUSE-Enceladus/public-cloud-info-service#74]
The images table is using incorrect primary keys in some cases. The keys should be as follows:

AlibabaImages
  - name, region

AmazonImages
  - name, region

GoogleImages
  - name, project

MicrosoftImages
  - name, environment

MicrosoftRegionMap
  - environment, region

OracleImages
  - id

**Comment by jeremy-moffitt** [comment]
Note, there is on-going discussion in email that may change the keys from what is specified above

**Comment by rtamalin** [comment]
The changes in #88 are the underpinnings to getting this work done.
