### ISSUE TITLE
Split DB schema migration and data import

### ISSUE THREAD

**Issue by jeremy-moffitt** [SUSE-Enceladus/public-cloud-info-service#77]
The automation pipeline for image updates will not do a data import each time the schema is updated. Currently an import is done with every migration. 

Acceptance Critera:
- its possible to do a schema migration without doing a data import

**Comment by rtamalin** [comment]
Technically this is possible right now, but only for existing DBs that already have schema defined. Once #88 lands we will be in a position to close this task out.
