### ISSUE TITLE
Handle google regions for image queries

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/public-cloud-info-service#8]
Now that the client and server can provide region information it is more obvious that the data for Google is inconsistent.

Because Google treats images by name and the name of images in all regions is the same the Google data has no region specific entries for images. However this results in empty queries when on the client side

```pint google images --active --region europe-north1```

is used. Now that the query of region names is possible it is obvious that this inconsistency exists. Server side we should handle this and return the proper image, i.e. for Google ignore the region setting and treat it as "global".

**Comment by jeremy-moffitt** [comment]
I believe the PR from Charu https://github.com/SUSE-Enceladus/public-cloud-info-service/pull/10 resolves this issue. Closing the ticket.
