### ISSUE TITLE
pint-ng supports split schema for servers

### ISSUE THREAD

**Issue by jeremy-moffitt** [SUSE-Enceladus/public-cloud-info-service#91]
The pint database schema is being updated to split the update and region servers into separate tables. PINT-NG needs to be able to continue to serve up the full set of servers after the database is updated. This may be done via a join or some other mechanism and should appear seamless to the end user. The script that imports the data needs to sort the servers into the appropriate tables based on the server type.

Acceptance Criteria:
- the server queries in pint continue to consistently return data for all server types after the server types are split into separate tables in the schema
- pint_server/data_update.py correctly sorts servers into the appropriate tables based on the server type

**Comment by rtamalin** [comment]
We have decided not to implement this feature after all.
